import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — RunTheMic",
};

export default function PrivacyPage() {
  return (
    <main className="mx-auto flex min-h-dvh max-w-3xl flex-col px-6 py-10">
      <header className="mb-10 flex items-center justify-between">
        <Link href="/" className="font-display text-xl font-bold tracking-tight text-gradient-neon">
          RunTheMic
        </Link>
        <Link href="/" className="text-sm text-muted-foreground hover:text-foreground">
          Back to home
        </Link>
      </header>

      <div className="flex flex-col gap-8 text-sm leading-relaxed text-muted-foreground">
        <div>
          <h1 className="font-display text-3xl font-bold text-foreground">Privacy Policy</h1>
          <p className="mt-2 text-xs">Last updated: September 19, 2026</p>
        </div>

        <p>
          RunTheMic (&quot;RunTheMic,&quot; &quot;we,&quot; &quot;us&quot;) helps people host karaoke nights: creating an
          event, sharing an RSVP link, and collaboratively building a YouTube playlist that guests can request
          songs to. This policy explains what information we collect, how we use it, and the choices you have.
        </p>

        <Section title="Information we collect">
          <p>
            <strong className="text-foreground">Organizers</strong> — when you create an account, we collect
            your name, email address, and a securely hashed password. If you sign in with Google, we receive
            your name, email, and profile picture from Google instead of a password.
          </p>
          <p>
            <strong className="text-foreground">Guests</strong> — RSVPing to an event doesn&apos;t require an
            account. We store the name you enter, an optional email address (only if you choose to provide
            one, to send you a confirmation), and any note you add, tied to a signed cookie in your browser
            rather than a login.
          </p>
          <p>
            <strong className="text-foreground">Event data</strong> — event details an organizer enters (name,
            date, location, description, flyer customizations) and the song queue built for that event
            (song titles, who requested them, and approval status).
          </p>
          <p>
            <strong className="text-foreground">YouTube connection</strong> — if an organizer connects a
            YouTube account (see below), we store which Google account is connected (its email address) and
            an encrypted OAuth refresh token used solely to manage that event&apos;s playlist on your behalf.
            We never see or store your Google password.
          </p>
          <p>
            <strong className="text-foreground">Basic technical data</strong> — standard server logs (IP
            address, timestamps, request paths) generated by our hosting provider for security and reliability,
            not used for tracking or advertising.
          </p>
        </Section>

        <Section title="YouTube API Services">
          <p>RunTheMic uses YouTube API Services.</p>
          <p>
            When an organizer connects their YouTube account from Settings, RunTheMic requests permission to
            manage playlists on that account (create a playlist for the event, and add or remove the songs
            guests request). This is a separate, optional step from signing in — logging into RunTheMic with
            Google never grants YouTube access on its own. An organizer can revoke this access at any time
            from{" "}
            <a
              href="https://myaccount.google.com/permissions"
              target="_blank"
              rel="noreferrer"
              className="text-primary underline underline-offset-2"
            >
              Google&apos;s security settings
            </a>
            , or by disconnecting YouTube from RunTheMic&apos;s Settings page.
          </p>
          <p>
            By using RunTheMic&apos;s YouTube integration, you also agree to be bound by the{" "}
            <a
              href="https://www.youtube.com/t/terms"
              target="_blank"
              rel="noreferrer"
              className="text-primary underline underline-offset-2"
            >
              YouTube Terms of Service
            </a>
            . For more on how Google handles your data, see the{" "}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noreferrer"
              className="text-primary underline underline-offset-2"
            >
              Google Privacy Policy
            </a>
            .
          </p>
        </Section>

        <Section title="How we use your information">
          <ul className="list-disc space-y-1 pl-5">
            <li>To operate the core features you use: events, RSVPs, flyers, and the song queue.</li>
            <li>To manage a connected YouTube playlist in sync with an event&apos;s song queue.</li>
            <li>To send transactional email — account verification and, if you opt in as a guest, an RSVP confirmation, or as an organizer, a notification when someone RSVPs.</li>
            <li>To keep the service secure and prevent spam or abuse (e.g. a bot-detection check on signup and RSVP forms).</li>
          </ul>
          <p>We don&apos;t sell your information, and we don&apos;t use it for advertising.</p>
        </Section>

        <Section title="Who we share data with">
          <p>We use a small number of third-party services to run RunTheMic, each only for its specific purpose:</p>
          <ul className="list-disc space-y-1 pl-5">
            <li><strong className="text-foreground">Google</strong> — sign-in and YouTube playlist management, as described above.</li>
            <li><strong className="text-foreground">Resend</strong> — delivering transactional email (verification, confirmations, notifications).</li>
            <li><strong className="text-foreground">Cloudflare</strong> — spam/bot filtering on public forms, and content delivery.</li>
            <li><strong className="text-foreground">Railway</strong> — application hosting and database infrastructure.</li>
          </ul>
        </Section>

        <Section title="Data retention and deletion">
          <p>
            Deleting an event permanently removes that event and everything tied to it — RSVPs, the song
            queue, flyer customizations, and its YouTube playlist link — immediately. To delete your organizer
            account entirely, contact us at the email below.
          </p>
        </Section>

        <Section title="Cookies">
          <p>
            We use a session cookie to keep organizers signed in, and a separate, per-event cookie so guests
            don&apos;t have to re-enter their RSVP. We don&apos;t use third-party advertising or tracking
            cookies.
          </p>
        </Section>

        <Section title="Children's privacy">
          <p>RunTheMic is not directed at children under 13, and we don&apos;t knowingly collect information from them.</p>
        </Section>

        <Section title="Changes to this policy">
          <p>
            If we make material changes to this policy, we&apos;ll update the date at the top of this page.
          </p>
        </Section>

        <Section title="Contact us">
          <p>
            Questions about this policy or your data?{" "}
            <a href="mailto:support@runthemic.com" className="text-primary underline underline-offset-2">
              support@runthemic.com
            </a>
          </p>
        </Section>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="font-display text-lg font-semibold text-foreground">{title}</h2>
      {children}
    </section>
  );
}
